In [1]:
print('Hello, World')

Hello, World


Đầu dòng - Indentation

In [2]:
x = 1
if x == 1:
  print('x là 1')
  #lenh in khi dieu kien x la dung

x là 1


Biến và kiểu

Không yêu cầu khai báo các biến trước khi sử dụng; có thể tạo các
biến bất khi khi nào cần.
Kiểu số: hỗ trợ integer và float

In [3]:
#ráng x = 7
myint = 7
print(myint)
myfloat = 7.0
print(myfloat)
#ép kiểu dữ liệu float
myfloat = float(myint)
print(myfloat)
#ép kiểu dữ liệu float
myint = int(myfloat)
print(myint)

7
7.0
7.0
7


Kiểu chuỗi (string): đặt trong dấu ngoặc đơn ’ hay
dấu ngoặc kép "

In [4]:
#rang chuoi va in
mystring = "hello, world!"
print(mystring)
mystring = "Let's talk about Python"
print(mystring)

hello, world!
Let's talk about Python


Có thể áp dụng các toán tử đơn giản cho các biến hoặc gán nhiều
biến đồng thời

In [7]:
b1 = 1
b2 = 2
b3 = b1 + b2
print(b3)

h = "Hello,"
w = "World!"
hw = h + " " +w
print(hw)

a,b = 3,4
print(a, b)

3
Hello, World!
3 4


Thêm giá trị biến số vào chuỗi với hàm format

In [8]:
b = 1/3 * 100
print("Bien khong dinh dang: {}%".format(b))
print('Bien dinh dang: {:.3f}%'.format(b))
print('Bien dinh dang dau cach: {:10.1f}%'.format(b))
c=2
print('Bien c  = {} va b = {:.3f}'.format(c,b))


Bien khong dinh dang: 33.33333333333333%
Bien dinh dang: 33.333%
Bien dinh dang dau cach:       33.3%
Bien c  = 2 va b = 33.333


Danh sách - List

Danh sách có thứ tự của bất kỳ loại kiểu dữ liệu gì của
biến → kết hợp nhiều biến khác loại; thường danh sách
chứa cùng loại kiểu. Một danh sách được đặt giữa dấu
ngoặc vuông [ ]

In [9]:
#tao mot list rong
ds = []
#them gia tri 1, 2, 3
ds.append(1); ds.append(2); ds.append(3)
#in ra list ds, in ra gia tri vi tri dau, in gia tri cuoi, in gia tri tu 2-3
print(ds); print(ds[0]); print(ds[-1]); print(ds[1:3])
for x in ds: #in gia tri danh sach ds
  print(x)

[1, 2, 3]
1
3
[2, 3]
1
2
3


Danh sách - List

Kiểm tra kiểu biến bằng isinstance. Ví dụ:
isinstance(x, float)

Nhận được số vòng lặp và giá trị từng phần tử bằng
enumerate. Ví dụ: for i, x in enumerate(ds)

Sắp xếp: sort

Số lượng các mục trong danh sách: len

Số lần một biến xuất hiện trong danh sách:

list.count(x)

In [32]:
names = ["An", 3234, 2342, 3323, "Yen", 234, "Cao", 734978234, "Lam", 2384]
print("So names trong danh sach: {}".format(len(names)))
new_names = []
for n in names:
  #kiem tra kieu bien
  if isinstance(n, str):
    #chon lai name la kieu chuoi
    new_names.append(n)
#Sap xep
new_names.sort()
print("So name la kieu chuoi: {}.".format(len(new_names)))
#nhan duoc so vong lap va gia tri tung phan tu
for i, n in enumerate(new_names):
  #In ten kem voi thu tu trong danh sach
  print('{}. {}'.format(i,n))

So names trong danh sach: 10
So name la kieu chuoi: 4.
0. An
1. Cao
2. Lam
3. Yen


Từ điển - Dictionaries

Tương tự mảng nhưng bao gồm cặp <khóa: giá trị>.
Mỗi giá trị lưu trữ trong từ điển được truy cập bằng
khóa của nó và giá trị có thể là bất kỳ loại đối tượng
nào. Từ điển được đặt trong

In [41]:
phonebook = {}
phonebook["An"] = {"Phone": "0903 794 794", "Email": 'an@email.com' }
phonebook["Binh"] = {"Phone": "0192 812 812", "Email": 'binh@email.com'}
phonebook["Cao"] = {"Phone": "0129 812 721", "Email": 'cao@email.com'}
print(phonebook)


{'An': {'Phone': '0903 794 794', 'Email': 'an@email.com'}, 'Binh': {'Phone': '0192 812 812', 'Email': 'binh@email.com'}, 'Cao': {'Phone': '0129 812 721', 'Email': 'cao@email.com'}}


Từ điển - Dictionaries

Duyệt từ điển bằng dùng .items()

In [42]:
#lay ra ten va dulieu(p,e)
for ten, dulieu in phonebook.items():
  print("{} co so dien thoai la {} va email la {}".format(ten, dulieu['Phone'], dulieu['Email']))

An co so dien thoai la 0903 794 794 va email la an@email.com
Binh co so dien thoai la 0192 812 812 va email la binh@email.com
Cao co so dien thoai la 0129 812 721 va email la cao@email.com


Từ điển - Dictionaries

Xóa dữ liệu bằng del hay pop

In [43]:
del phonebook["An"]
# Iterate over a copy of the dictionary when deleting items
for ten, dulieu in phonebook.items():
  print("{} co so dien thoai la {} va email la {}".format(ten, dulieu['Phone'], dulieu['Email']))

  binh_data = phonebook.pop("Binh")
  print(binh_data)

  # The second loop should also iterate over a copy if modifications happen inside
  for ten, dulieu in phonebook.items():
    print('{} co so dien thoai la {} va email la {}'.format(ten, dulieu['Phone'], dulieu['Email']))

Binh co so dien thoai la 0192 812 812 va email la binh@email.com
{'Phone': '0192 812 812', 'Email': 'binh@email.com'}
Cao co so dien thoai la 0129 812 721 va email la cao@email.com


RuntimeError: dictionary changed size during iteration

Từ điển - Dictionaries

.get("Key", default). default: có thể là bất kỳ biến gì
hoặc True/False. Nếu bỏ trống thì kết quả là False nếu
không tìm thấy

In [44]:
binh_data = phonebook.get("Binh", False)
if binh_data:
  print("Thong tin binh: {} va email la {}".format(ten, binh_data['Phone'], binh_daya['Email']))
else:
  print('Khong co du lieu')

Khong co du lieu


Toan tu

In [45]:
x = 1 + 3/2 * 0.4
y = 7 ** 2
z = 12%3
print(x, y ,z )

1.6 49 0


In [46]:
even_numbers = [2,4,6,8]
uneven_numbers = [1,3,5,7]
all_numbers = uneven_numbers + even_numbers
print(all_numbers)
#lap lai dnah sach
print([1,2,3] * 3)

[1, 3, 5, 7, 2, 4, 6, 8]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [48]:
#cong chuoi
elloworld = 'Hello,' + " " + "World!"
print(helloworld)
manyhellos = "Hello " * 10
print(manyhellos)


Hello, World!
Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello 


In [49]:
str_x = "Hello, World"
print("Chieu dai chuoi: {}".format(len(str_x)))
print("Chi muc cua 'o' dau tien: {}".format(str_x.index('o')))
print("So 'o': {}".format(str_x.count('o')))

Chieu dai chuoi: 12
Chi muc cua 'o' dau tien: 4
So 'o': 2


In [52]:
print('Chuoi con gom tu thu 2 den 5 la" {}'.format(str_x[2:6]))
print("Chuoi con duyet bo qua 1 ky tu (3,5,7,..): {}".format(str_x[3:-2:2]))
print("Chuoi dao nguoc: {}".format(str_x[::-1]))
print("Bat dau voi 'Hello': {}".format(str_x.startswith('Hello')))
print("Ket thuc voi 'Hello': {} ".format(str_x.endswith('Hello')))
print("Chua 'Goodbye':{}".format('Goodbye' in str_x))
print("Tach chuoi: {}".format(str_x.split(" ")))

Chuoi con gom tu thu 2 den 5 la" llo,
Chuoi con duyet bo qua 1 ky tu (3,5,7,..): l,Wr
Chuoi dao nguoc: dlroW ,olleH
Bat dau voi 'Hello': True
Ket thuc voi 'Hello': False 
Chua 'Goodbye':False
Tach chuoi: ['Hello,', 'World']


In [53]:
x=2
y=10
if x > 2:
  print(" x > 2")
elif x ==2 and y > 50:
  print("x == 2 vaf y > 50")
elif x < 10 or y > 50:
  print('x < 10 hoac y > 50')
else:
  print("Nothing")
name_list1 = ['Join', 'Jill']
name_list2 = ['Join', 'Jill']
print(not(name_list1 == name_list2))
print(name_list1 == name_list2)
print(name_list1 is name_list2)

x < 10 hoac y > 50
False
True
False


In [54]:
for i, x in enumerate(range(2,8,2)):
  print('{}.Khong {}'.format(i,x))

0.Khong 2
1.Khong 4
2.Khong 6


In [56]:
count = 0
print('Break and while conditional')
while True:
  print(count)
  count +=1
  if count >=3:
    break
  print("Continue")
  for x in range(4):
    if (x+1) % 2 == 0:
      continue
    print(x)

Break and while conditional
0
Continue
0
2
1
Continue
0
2
2


List comprehension

Cách nhanh chóng để lọc hoặc chỉnh sửa một danh sách
dựa trên một số tiêu chí.

In [59]:
sentence = 'for the song and the sword aer birthrights sold to userer, but I am the last lone highwayman and I am the last adventurer '
words = sentence.split()
word_lengths = []
for word in words:
  if word!='the':
    word_lengths.append(len(word))
print(word_lengths)

#the exact same thing can be achieved with a list comperhensi
word_lengths= [len(word) for word in sentence.split(' ') if word != 'the' ]
print(word_lengths)

[3, 4, 3, 5, 3, 11, 4, 2, 7, 3, 1, 2, 4, 4, 10, 3, 1, 2, 4, 10]
[3, 4, 3, 5, 3, 11, 4, 2, 7, 3, 1, 2, 4, 4, 10, 3, 1, 2, 4, 10, 0]


In [64]:
def print_list(my_list):
  for i in range(5):
    try:
      print(my_list[i])
    except IndexError:
      print(0)
print_list([1,2,3,4])

1
2
3
4
0


In [70]:
def print_zero(zero):
  if zero != 0:
    raise (ValueError, "Not Zero!")
  print(zero)
print_zero(10)

TypeError: exceptions must derive from BaseException

Tập hợp - Set

Bộ là danh sách không có mục nhập trùng lặp.

In [71]:
set_one = set(["Alice", "Carol", "Dan", "Eve", "Heidi"])
set_two = set(["Bob", "Dan", "Eve", "Grace", "Heidi"])
print("set_one giao voi set_two: {}".format(set_one.intersection(set_two)))
print("set_two giao voi set_one: {}".format(set_two.intersection(set_one)))
print("set_one khac biet doi xung: {}".format(set_one.symmetric_difference(set_two)))
print("set_one khac voi set_two: {}".format(set_one.difference(set_two)))
print("set_two khac voi set_one: {}".format(set_two.difference(set_one)))
print("set_one khac voi set_one: {}".format(set_two.union(set_two)))
print("set_two hop voi set_one: {}".format(set_two.union(set_one)))

set_one giao voi set_two: {'Dan', 'Eve', 'Heidi'}
set_two giao voi set_one: {'Dan', 'Eve', 'Heidi'}
set_one khac biet doi xung: {'Alice', 'Carol', 'Bob', 'Grace'}
set_one khac voi set_two: {'Alice', 'Carol'}
set_two khac voi set_one: {'Bob', 'Grace'}
set_one khac voi set_one: {'Eve', 'Dan', 'Bob', 'Grace', 'Heidi'}
set_two hop voi set_one: {'Eve', 'Alice', 'Grace', 'Carol', 'Dan', 'Bob', 'Heidi'}


Numpy là thư viện xử lý mảng đa chiều với các tính năng

Kiểm tra tự động: kiểm tra tính nhất quán dữ liệu

Lưu trữ liền kề: lưu trữ dữ liệu trong các vị trí bộnhớ liền kề → ít dung lượng hơn

Số học vector nhanh hơn

Để sử dụng cần (as np được dùng như bí danh để tiện
việc sử dụng về sau)

In [72]:
import numpy as np

Mảng 1D

Mảng numpy gồm 02 biến trạng thái quan trọng: dtype
(kiểu) và shape (hình trạng)

Khởi tạo: numpy.array(list)

In [74]:
v = np.array([1,4,9,3,2])
print('Mang 1D trong numpy la %s' %v)
print("dtype cua mang numpy la %s" %v.dtype)
print("shape la %s"%v.shape)

Mang 1D trong numpy la [1 4 9 3 2]
dtype cua mang numpy la int64
shape la 5


Khởi tạo qua arange: numpy.arange([start, ]stop,
[step, ] dtype=None)

In [76]:
v1 = np.arange(5)
print("Tao mot mang numpy bang arange (stop=5) : %s"%v1)
v2 = np.arange(2,5)
print("tao mot mang numpy bang arrange (start=2, stop=5):%s"%v2)
v3= np.arange(0, -10,-2)
print('Tao mot mang numpy bang arrange(start=0, sttop=-10, step=-2): %s'%v3)


Tao mot mang numpy bang arange (stop=5) : [0 1 2 3 4]
tao mot mang numpy bang arrange (start=2, stop=5):[2 3 4]
Tao mot mang numpy bang arrange(start=0, sttop=-10, step=-2): [ 0 -2 -4 -6 -8]


Khởi tạo từ List của List: numpy.array ( object,
dtype=None )

In [77]:
pymat = [[1,2,3],[4,5,6]]
npmat = np.array(pymat)
print('ma tran numpy la \n%s'%npmat)
print('Phien ban phang cua ma tran numpy is %s'%npmat.flatten())


ma tran numpy la 
[[1 2 3]
 [4 5 6]]
Phien ban phang cua ma tran numpy is [1 2 3 4 5 6]


Khởi tạo với zeros/ones:

numpy.zeros(shape, dtype=float)

numpy.ones(shape, dtype=float)

In [78]:
#mang 2 chieu 4
mat_zeros = np.zeros(shape=(2,4))
print('Ma tran 0 voi kich thuoc %s la \n%s \n'%(mat_zeros.shape, mat_zeros))
mat_ones = np.ones(shape=(2,3))
print("Ma tran 1 voi kich thuoc %s is \n%s \n"%(mat_ones.shape, mat_ones))

Ma tran 0 voi kich thuoc (2, 4) la 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

Ma tran 1 voi kich thuoc (2, 3) is 
[[1. 1. 1.]
 [1. 1. 1.]] 



Mảng 2D

Khởi tạo với giá trị ngẫu nhiên:

numpy.random.random(size=None,)

numpy.random.randint(low, high, size=None, dtype=’I’)

In [79]:
mat1 = np.random.random(size=(3,2))
print("ma tran sinh tu numpy.random.random la \n%s" %mat1)
mat2 = np.random.randint(low=0, high=3, size=(3,2))
print('ma tran sinh tu numpy.random.random la \n%s'%mat2)
mat3 = np.random.randn(3,2)
print('ma tran sinh tu numpy.ramdom.randm la \n%s' %mat3)


ma tran sinh tu numpy.random.random la 
[[0.76031182 0.44288857]
 [0.17613792 0.32949959]
 [0.2482403  0.51768883]]
ma tran sinh tu numpy.random.random la 
[[2 0]
 [1 2]
 [0 0]]
ma tran sinh tu numpy.ramdom.randm la 
[[ 0.49975947 -0.9525462 ]
 [-0.27179778  0.48473108]
 [-0.89691608  2.41407315]]


Cắt và lập chỉ mục trong Numpy

Numpy có bắt đầu bằng 0

Cắt (Slicing) tổng quát: [start]:[end]:[jump]

Chỉ nhảy: ::2

Chỉ điểm kết thúc: :5

Điểm bắt đầu và nhảy: 2::-1

Điểm kết thúc và nhảy: :5:2

In [80]:
#Bỏ n phần tử: vec[:-n]
import numpy as np
vec = np.arange(10)
vec1 = vec[:-3]
print('Ket qua sau khi bo 03 phan tu cuoi tu rang(10): \n%s' %vec1)


Ket qua sau khi bo 03 phan tu cuoi tu rang(10): 
[0 1 2 3 4 5 6]


Cắt và lập chỉ mục trong Numpy

In [82]:
#Truy cập phần tử tại vị trí chẵn: vec[::2]
vec1 = np.arange(0, 20, 3)
print( 'Mang ban dau la %s\n' %vec1)
vec2 = vec1[::2]
print('Phan tu tai vi tri chan %s\n' %vec2)

Mang ban dau la [ 0  3  6  9 12 15 18]

Phan tu tai vi tri chan [ 0  6 12 18]



In [83]:
#Truy cập phần tử theo hướng ngược lại: vec[::-1]
vec1 = np.arange(0,20,3)
print('Mang ban dau la %s\n' %vec1)
vec2 = vec1[::-1]
print('Mang sau khi dao nguoc lai %s\n' %vec2)

Mang ban dau la [ 0  3  6  9 12 15 18]

Mang sau khi dao nguoc lai [18 15 12  9  6  3  0]



In [84]:
#Truy cập theo khoảng chỉ mục: vec[a:b]
vec1 = np.arange(0,20,3)
print('Mang ban dau la %s \n' %vec1)
vec2 = vec1[2:5]
print('Mang gom phan tu [2:5) la %s\n]' %vec2)

Mang ban dau la [ 0  3  6  9 12 15 18] 

Mang gom phan tu [2:5) la [ 6  9 12]
]


In [85]:
#Truy cập theo tập chỉ mục: vec[idxlist]
idx=[0,1,5]
vec1 = np.arange(0,20,3)
print('Mang ban dau la %s\n' %vec1)
vec2 = vec1[idx]
print('Ma tran con duoc tao bnag ca chi muc %s la %s\n' %(idx,vec2))


Mang ban dau la [ 0  3  6  9 12 15 18]

Ma tran con duoc tao bnag ca chi muc [0, 1, 5] la [ 0  3 15]



In [86]:
#tao ma tran con
mat = np.random.randint(0,6,(3,5))
#Tao ma tran voi 2 dong dau, 3 cot cuoi
submat1 = mat[0:2, -2:]
print('Ma tran ban dau \n%sn' %mat)
print('Ma tran con voi 2 dong dau va 2 cot cuoi \n%s\n' %submat1)
submat2 = mat[:,3:-1]
print('Sau khi lat cac cot ma tran: \n%s\n' %submat2)

Ma tran ban dau 
[[4 3 1 0 4]
 [0 3 0 0 0]
 [4 3 2 4 4]]n
Ma tran con voi 2 dong dau va 2 cot cuoi 
[[0 4]
 [0 0]]

Sau khi lat cac cot ma tran: 
[[0]
 [0]
 [4]]



In [87]:
#Tách ma trận ngang: numpy.hsplit(array, indices_or_sections) chia ma trận trên mặt phẳng ngang, số hàng không đổi
mat = np.random.randint(0,6,(3,7))
sp1, sp2, sp3 = np.hsplit(mat,[4,6])
print('Original matrix of shape %s, is \n%s\n' %(mat.shape, mat))
print('First split of shape %s, is ]\n%s\n'%(sp1.shape, sp1))
print('Second split of shape %s, is \n%s\n'%(sp2.shape, sp2))
print('Third split of shape %s, is \n%s\n'%(sp3.shape, sp3))

Original matrix of shape (3, 7), is 
[[0 0 0 0 3 2 1]
 [3 2 3 4 0 3 5]
 [0 2 4 5 3 5 0]]

First split of shape (3, 4), is ]
[[0 0 0 0]
 [3 2 3 4]
 [0 2 4 5]]

Second split of shape (3, 2), is 
[[3 2]
 [0 3]
 [3 5]]

Third split of shape (3, 1), is 
[[1]
 [5]
 [0]]



In [89]:
#Tách ma trận dọc: numpy.vsplit(array, indices_or_sections)chia nhỏ ma trận trên mặt phẳng thẳng đứng, số cột không đổi
mat = np.random.randint(0,6,(3,7))
sp1,sp2 = np.vsplit(mat,[1])
print("Original matrix of shape %s, is \n%s\n" %(mat.shape, mat))
print("First split of shape %s, is \n%s\n" %(sp1.shape, sp1))
print("Second split of shape %s, is \n%s\n" %(sp2.shape, sp2))

Original matrix of shape (3, 7), is 
[[5 2 5 2 5 0 0]
 [3 2 0 3 0 5 0]
 [1 3 5 0 2 4 4]]

First split of shape (1, 7), is 
[[5 2 5 2 5 0 0]]

Second split of shape (2, 7), is 
[[3 2 0 3 0 5 0]
 [1 3 5 0 2 4 4]]

